# Generated by Django 3.2 on 2021-05-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='connected',
        ),
    ]
