# Generated by Django 3.1.5 on 2021-02-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='light_theme',
        ),
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=5, verbose_name='theme'),
        ),
    ]
