# Generated by Django 3.1.5 on 2021-02-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_mail_unread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='file',
        ),
    ]
