# Generated by Django 3.1.5 on 2021-02-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_new',
        ),
    ]
