# Generated by Django 3.1.5 on 2021-02-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='image/text.png', upload_to='data/users/pics'),
        ),
    ]
