# Generated by Django 3.1.5 on 2021-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
