# Generated by Django 3.1.5 on 2021-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_mail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='url',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
