# Generated by Django 3.1.5 on 2021-02-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210219_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='url',
            field=models.SlugField(allow_unicode=True, auto_created=True, null=True),
        ),
    ]
