# Generated by Django 3.2 on 2021-04-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210430_0428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.RemoveField(
            model_name='account',
            name='about',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_image',
        ),
    ]
